# Generated by Django 3.2.8 on 2021-12-03 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_carona', models.DateTimeField()),
                ('valor_carona', models.FloatField()),
                ('vagas_disponiveis', models.IntegerField()),
                ('observacoes', models.CharField(max_length=255, null=True)),
                ('cep_origem', models.CharField(max_length=8)),
                ('endereco_origem', models.CharField(max_length=255)),
                ('num_origem', models.CharField(max_length=8)),
                ('cidade_origem', models.CharField(max_length=50)),
                ('estado_origem', models.CharField(max_length=50)),
                ('cep_destino', models.CharField(max_length=8)),
                ('endereco_destino', models.CharField(max_length=255)),
                ('num_destino', models.CharField(max_length=8)),
                ('cidade_destino', models.CharField(max_length=50)),
                ('estado_destino', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Carona_Passageiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_pessoas', models.IntegerField()),
                ('tipo_pagamento', models.CharField(choices=[('cartao', 'Freshman'), ('dinheiro', 'Sophomore')], max_length=20)),
                ('id_carona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caronas.carona')),
            ],
        ),
        migrations.CreateModel(
            name='Condutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_carteira_motorista', models.CharField(max_length=15)),
                ('validade_carteira', models.DateField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('senha', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('telefone', models.CharField(max_length=11)),
                ('cep', models.CharField(max_length=8)),
                ('estado', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=255)),
                ('num_residencia', models.CharField(max_length=8)),
                ('complemento', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante_veic', models.CharField(max_length=50)),
                ('modelo_veic', models.CharField(max_length=50)),
                ('placa_veic', models.CharField(max_length=7)),
                ('cor_veic', models.CharField(max_length=50)),
                ('capacidade_veic', models.IntegerField()),
                ('apelido_veic', models.CharField(max_length=50, null=True)),
                ('id_condutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caronas.condutor')),
            ],
        ),
        migrations.CreateModel(
            name='Passageiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('status_pas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caronas.status')),
            ],
        ),
        migrations.CreateModel(
            name='Log_Carona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_log', models.DateTimeField(default=django.utils.timezone.now)),
                ('comentario_log', models.CharField(max_length=255, null=True)),
                ('id_carona_passageiros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caronas.carona_passageiros')),
                ('status_carona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caronas.status')),
            ],
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_denuncia', models.CharField(max_length=20)),
                ('comentario_denuncia', models.CharField(max_length=255, null=True)),
                ('id_carona_passageiros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caronas.carona_passageiros')),
                ('status_denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caronas.status')),
            ],
        ),
        migrations.CreateModel(
            name='Conta_Cond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco_conta', models.CharField(max_length=50)),
                ('agencia_conta', models.CharField(max_length=4)),
                ('num_conta', models.CharField(max_length=9)),
                ('apelido_conta', models.CharField(max_length=20, null=True)),
                ('id_condutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caronas.condutor')),
            ],
        ),
        migrations.AddField(
            model_name='condutor',
            name='status_cond',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caronas.status'),
        ),
        migrations.CreateModel(
            name='Cartao_Passageiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cart', models.CharField(max_length=16)),
                ('validade_cart', models.CharField(max_length=6)),
                ('cvn_cart', models.CharField(max_length=3)),
                ('nome_cart', models.CharField(max_length=255)),
                ('apelido_cart', models.CharField(max_length=30, null=True)),
                ('id_passageiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caronas.passageiro')),
            ],
        ),
        migrations.AddField(
            model_name='carona_passageiros',
            name='id_cartao_passageiro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='caronas.cartao_passageiro'),
        ),
        migrations.AddField(
            model_name='carona_passageiros',
            name='id_passageiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caronas.passageiro'),
        ),
        migrations.AddField(
            model_name='carona',
            name='id_condutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caronas.condutor'),
        ),
        migrations.AddField(
            model_name='carona',
            name='id_veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caronas.veiculo'),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_avaliacao', models.IntegerField()),
                ('comentario_avaliacao', models.CharField(max_length=255, null=True)),
                ('horario_avaliacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_carona_passageiros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caronas.carona_passageiros')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('status_adm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caronas.status')),
            ],
        ),
        migrations.CreateModel(
            name='Verifica_Veic',
            fields=[
                ('id_veiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='caronas.veiculo')),
                ('comentario_verveic', models.CharField(max_length=255, null=True)),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caronas.admin')),
                ('status_verveic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caronas.status')),
            ],
        ),
        migrations.CreateModel(
            name='Verifica_Cond',
            fields=[
                ('id_condutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='caronas.condutor')),
                ('comentario_vercond', models.CharField(max_length=255, null=True)),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caronas.admin')),
                ('status_vercond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caronas.status')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado_Denuncia',
            fields=[
                ('id_denuncia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='caronas.denuncia')),
                ('parecer_resden', models.CharField(max_length=20)),
                ('comentario_resden', models.CharField(max_length=255, null=True)),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caronas.admin')),
            ],
        ),
    ]
