# Generated by Django 3.2.7 on 2021-12-09 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caronas', '0004_rename_users_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nome',
        ),
    ]
