# Generated by Django 3.2.8 on 2021-12-09 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caronas', '0005_remove_profile_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passageiro',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='passageiro',
            name='status_pas',
        ),
        migrations.RemoveField(
            model_name='condutor',
            name='status_cond',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_condutor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_passageiro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='caronas.status'),
        ),
        migrations.AlterField(
            model_name='carona_passageiros',
            name='id_passageiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caronas.profile'),
        ),
        migrations.AlterField(
            model_name='cartao_passageiro',
            name='id_passageiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caronas.profile'),
        ),
        migrations.AlterField(
            model_name='condutor',
            name='id_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='caronas.profile'),
        ),
        migrations.AlterField(
            model_name='resultado_denuncia',
            name='id_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caronas.profile'),
        ),
        migrations.AlterField(
            model_name='verifica_cond',
            name='id_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caronas.profile'),
        ),
        migrations.AlterField(
            model_name='verifica_veic',
            name='id_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caronas.profile'),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Passageiro',
        ),
    ]
