# Generated by Django 3.2.7 on 2021-12-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caronas', '0007_alter_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao_passageiro',
            name='validade_cart',
            field=models.CharField(max_length=7),
        ),
    ]
