# Generated by Django 3.2.7 on 2021-12-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caronas', '0008_alter_cartao_passageiro_validade_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='carona',
            name='bairro_destino',
            field=models.CharField(default='abcd', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carona',
            name='bairro_origem',
            field=models.CharField(default='abcd', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='bairro',
            field=models.CharField(default='efgh', max_length=255),
            preserve_default=False,
        ),
    ]
