# Generated by Django 3.2.8 on 2021-12-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caronas', '0008_alter_cartao_passageiro_validade_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carona_passageiros',
            name='tipo_pagamento',
            field=models.CharField(choices=[('cartao', 'Cartão'), ('dinheiro', 'Dinheiro')], max_length=20),
        ),
    ]
