# Generated by Django 3.2.7 on 2021-12-12 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caronas', '0009_alter_carona_passageiros_tipo_pagamento'),
        ('caronas', '0009_auto_20211212_2021'),
    ]

    operations = [
    ]
