# Generated by Django 3.2.7 on 2021-12-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caronas', '0010_merge_20211212_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carona',
            name='valor_carona',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
