# Generated by Django 3.2.8 on 2021-12-15 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caronas', '0013_auto_20211214_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifica_veic',
            name='id_admin',
        ),
        migrations.RemoveField(
            model_name='verifica_veic',
            name='id_veiculo',
        ),
        migrations.RemoveField(
            model_name='verifica_veic',
            name='status_verveic',
        ),
        migrations.DeleteModel(
            name='Verifica_Cond',
        ),
        migrations.DeleteModel(
            name='Verifica_Veic',
        ),
    ]
